### PR TITLE
Use cloud storage for documents

### PR DESCRIPTION
**Pull request by skelz0r**
Storing files on server is not a good practice for a lot of reasons.
This pull request introduces a S3 storage backend for documents, which has replication by design, which makes it resilient.

Some changelogs:

* Recycle old documents route (which is not use by the frontend) to mirror/mask the actual cloud storage url
* Some refactor for content validation (not the same way to read content between file and s3 with carrierwave, dunno why)
* Scout clean with `ApplicationSerializer`

### CODE REVIEW

**Comment by skelz0r** [comment]
ça se lit commit / commit

**Review by Un3x — APPROVED** [review]
Stylé

**Comment by skelz0r** [comment]
J'ai déployé en prod pour tester (c'est peu critique fonctionnellement vu que le put fonctionne, ça sera le read le temps de la migration de données qui pourra planter)

**Comment by skelz0r** [comment]
(le script PI https://gist.github.com/skelz0r/54fcdcd83537cf9dfbae306b749f96e1 )

**Comment by skelz0r** [comment]
all green, je merge vu que ça fonctionne (testé le read en prod, le put/read en sandbox)

Related https://github.com/etalab/very_ansible/pull/416/commits/a96853fd8490371f46fbecd781b3ccfdad67a977

**Pull request merged**
